=== HMLeao/LDD-II/Atividades/1 XML Schema/livros/livraria.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="livraria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="livro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="title">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute  name="lang">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:pattern value="([a-z]{2})" />
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="author">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="name" minOccurs="0" type="xs:string" />                                    
                                        <xs:element name="country" minOccurs="0" type="xs:string" />                                    
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="year">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:totalDigits value="4" />
                                        <xs:minInclusive value="100" />
                                        <xs:maxInclusive value="3000" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="status" type="xs:string" />    
                            <xs:element name="price" type="xs:string" />
                        </xs:all>
                        <xs:attribute name="category" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="([A-Z]+)" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== HMLeao/LDD-II/Atividades/1 XML Schema/livros/livraria.xml
<?xml version="1.0" encoding="UTF-8"?>
<livraria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="livraria.xsd">
    <livro category="COOKING">
        <title lang="en">Everyday Italian</title>
        <author>
            <name>J K. Rowling</name>
            <country>USA</country>
        </author>
        <year>2005</year>
        <price>30.00</price>
        <status>OFF</status>
    </livro>
    <livro category="CHILDREN">
        <title lang="en">Harry Potter</title>
        <author>
            <name>J K. Rowling</name>
            <country>USA</country>
        </author>
        <year>2005</year>
        <status>ON</status>
        <price>29.99</price>
    </livro>
    <livro category="WEB">
        <author>
            <name>Erik T. Ray</name>
            <country>Canada</country>
        </author>
        <year>2003</year>
        <price>39.95</price>
        <title lang="en">Learning XML</title>
        <status>ON</status>
    </livro>
    <livro category="WEB">
        <title lang="en">Learning XML DTD</title>
        <author>Erik T. Ray</author>
        <status>ON</status>
        <year>2005</year>
        <price>32.50</price>
    </livro>
</livraria>
